### ISSUE TITLE
What is this project about?

### ISSUE THREAD

**Issue by aahoo** [oaqa/CPA#5]
Hey guys,
Could you please provide more documentation about this project. It seems super interesting to me. I am applying for a PhD position in which I should use NLP to interrogate BIM models. There will be a lot of IoT stuff. If I get the position, this project can be a good starting point and I can actively contribute.

**Comment by mgrabmair** [comment]
I am afraid this is a CMU-internal project that will be made a private repository within the coming days. Are you affiliated with Carnegie Mellon University?

**Comment by aahoo** [comment]
At DIT in Dublin. That's a pity that this is gonna go private. I wish you good luck with the project :)
